'use strict';
const root=document.getElementById('app');
const key='unfallmanagement-bgn-demo-v1';
const seed={incidents:[{id:'U-2026-017',date:'2026-09-12',area:'Verpackung',type:'Beinaheunfall',summary:'Rutschgefahr durch Reinigungsflüssigkeit im Verkehrsweg',status:'Untersuchung läuft'},{id:'U-2026-014',date:'2026-08-21',area:'Technik',type:'Arbeitsunfall',summary:'Handverletzung bei Instandhaltungsarbeit – Musterfall',status:'Maßnahmen offen'}],actions:[{id:'M-104',title:'Absperr- und Freigabeprozess Reinigung präzisieren',owner:'Schichtleitung',due:'2026-10-05',hierarchy:'O – Organisatorisch',status:'offen'},{id:'M-098',title:'Wirksamkeitskontrolle Unterweisung durchführen',owner:'EHS',due:'2026-09-30',hierarchy:'O – Organisatorisch',status:'in Bearbeitung'}]};
let data;try{data=JSON.parse(localStorage.getItem(key))||structuredClone(seed);}catch{data=structuredClone(seed);}
const save=()=>localStorage.setItem(key,JSON.stringify(data));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){
 root.innerHTML=`<header style="padding:18px 24px;background:#0b3b46;color:white;display:flex;justify-content:space-between;gap:16px;align-items:center"><div><strong style="font-size:20px">Unfall- & Maßnahmenmanagement</strong><div style="opacity:.8;font-size:12px">Musterwerk Lebensmittel GmbH</div></div><span>BGN Demo · lokal</span></header><main style="padding:24px;max-width:1200px;margin:auto;font:14px/1.45 system-ui"><section style="padding:12px 14px;background:#fff8df;border:1px solid #efd27b;border-radius:10px;margin-bottom:20px"><b>Präsentationsmodus.</b> Alle Personen- und Ereignisdaten sind fiktiv. Keine Backend- oder E-Mail-Funktion. <button id="reset" style="float:right">Demo zurücksetzen</button></section><h1>Ereignisse und Maßnahmen</h1><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin:20px 0"><article style="padding:16px;background:white;border:1px solid #dce2e7;border-radius:12px"><small>Ereignisse</small><h2>${data.incidents.length}</h2></article><article style="padding:16px;background:white;border:1px solid #dce2e7;border-radius:12px"><small>Offene Maßnahmen</small><h2>${data.actions.filter(x=>x.status!=='erledigt').length}</h2></article></div><h2>Unfall-/Ereignismanagement</h2><div style="display:grid;gap:10px">${data.incidents.map(x=>`<article style="padding:14px;background:white;border:1px solid #dce2e7;border-radius:10px"><b>${esc(x.id)} · ${esc(x.type)}</b><div>${esc(x.summary)}</div><small>${esc(x.date)} · ${esc(x.area)} · ${esc(x.status)}</small></article>`).join('')}</div><h2 style="margin-top:28px">Maßnahmenmanagement</h2><div style="display:grid;gap:10px">${data.actions.map(x=>`<article style="padding:14px;background:white;border:1px solid #dce2e7;border-radius:10px"><b>${esc(x.id)} · ${esc(x.title)}</b><div>${esc(x.hierarchy)} · Verantwortlich: ${esc(x.owner)} · Termin: ${esc(x.due)}</div><button data-done="${esc(x.id)}">${x.status==='erledigt'?'Erledigt ✓':'Als erledigt markieren'}</button></article>`).join('')}</div></main>`;
 document.querySelector('#reset').onclick=()=>{localStorage.removeItem(key);location.reload();};
 document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{const x=data.actions.find(a=>a.id===b.dataset.done);if(x){x.status='erledigt';save();render();}});
}
save();render();